languageCode = "en-us"
title = "Rohan's Website"
baseurl = "https://swarnendurohanguptawebsite.firebaseapp.com/"
theme = "aerial"

[params]
  name = "Swarnendu Rohan Gupta"
  about = "Full Stack Developer &nbsp;&bull;&nbsp; World Traveller &nbsp;&bull;&nbsp; Excited for new challenges"
  copyright = "2018"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/S.RohanG6"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/Rohan_Gupta6"

[[params.social]]
  medium = "Linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/rohan-gupta-27b5b768/"


[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/srgupta5328"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "https://srgupta5328@gmail.com"
